config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "ecommerces#index"
  get '/guest', to: 'auths#guest_login', as: 'guest_login'
  get '/forget_password', to: 'auths#forget_password', as: 'forget_password'
  post '/validate', to: 'auths#validate_user', as: 'validate_user'
  resources :auths
  resources :ecommerces
  resources :carts
  get '/logout', to: 'auths#log_out', as: 'logout'
  get '/add', to: 'ecommerces#add_product', as: 'add_product'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :carts, dependent: :destroy
  has_one_attached :image , dependent:  :destroy

  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :product_description, presence: true
  validates :image , presence: true

  def self.import(file)
    counter =0
    CSV.foreach(file.pathmap, headers: true) do |row|
      if counter  <= 400
        begin
          product = Product.new(title:row['product_name'],manufacturer: row['manufacturer'],price: row['price'],product_description: row['product_information'], description: row['description'],user: User.first)
          product.image.attach(io: File.open("./app/assets/images/#{rand(1..5)}.jpg"), filename: "#{rand(1..5)}.jpg")
          product.save

        rescue StandardError => e
          print e
        end
      end
      counter  = counter + 1
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password, confirmation: { case_sensitive: true }
  validates :email, uniqueness: true
  has_many :carts
  has_many :products


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_session
  def initialize_session
    if session[:current_user].nil?
      session[:current_user] = nil
      session[:cart] ||= []
    end
    if session[:data_scrape].nil?
      session[:data_scrape] = nil
    end
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
  def index
    if session[:data_scrape].nil?
      Product.destroy_all
      file = Dir.glob("#{Rails.root}/public/product/data.csv")
      file.each do |file|
        Product.import(file)
        session[:data_scrape] = true
      end
      1.upto(200) do |i|
        Cart.create!(
            user_id: "#{i}",
            product_id: "#{i}"
        )
        end
    end
  end

  def new
    @user = User.new
  end

  def forget_password

  end

  def guest_login
    session[:current_user] = [{ "role": "guest"}]
    redirect_to ecommerces_path
  end

  def validate_user
    @user = User.where(email: params[:email], password: params[:password])
    if @user.present?
      session[:current_user] = @user
      flash[:notice] = "Welcome to the Ecommerce Website where you find everything"
      redirect_to root_path
    else
      flash[:alert] = "Please check the credentials"
      redirect_to auths_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "You have been register successfully Thank!"
      redirect_to auths_path
    else
      render new_auth_path
    end
  end

  def log_out
    session[:current_user].clear
    flash[:alert] = "you are logout from the website"
    redirect_to auths_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,:password_confirmation)
  end

  def permit_login_params
    params.permit[:email,:password]
  end

  def check_user_sign_up
    if session[:current_user].nil?
      redirect_to auths_path
    end
  end



end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :check_user_sign_up

  def index
    @cart = Cart.all
  end

  def create

  end

  def new
    @product = "asd"
    session[:cart] << @product unless session[:cart].include?(@product)
    @cart_product_counter =  session[:cart].count
  end

  def delete
    session[:cart] = session[:cart].reject { |product| product.id == params[:id].to_i } if params[:id].present?
    @cart_product_counter =  session[:cart].count
  end

  def show
    @products_row = Product.limit(4)
    @product =   Product.find(params[:id]) if params[:id].present?
  end

  private
  def check_user_sign_up
    if session[:current_user].nil? || session[:guest_login] == true
      redirect_to auths_path
    end
  end
end

app/controllers/ecommerces_controller.rb
class EcommercesController < ApplicationController
  before_action :check_user_sign_up
  def index
    search
    if params[:search_name]
      @products = Product.where("title LIKE ?", "%#{params[:search_name].titleize}%").paginate(page: params[:page], per_page: 30)
      session[:search_name].clear
    else
      @products = Product.paginate(page: params[:page], per_page: 30)
    end
  end


  def new
    @product =  Product.new
  end

  def create
    @product  =  User.find(session[:current_user][0]['id']).products.new(product_params)
    if @product.save
      session[:notice] = "Product added successfully"
      redirect_to ecommerces_path
    else
      render 'new'
    end
  end

  def show
    @products_row = Product.limit(4)
    @product =   Product.find(params[:id]) if params[:id].present?
  end

  def check_user_sign_up
    if session[:current_user].nil?
      redirect_to auths_path
    end
  end

  def product_params
    params.require(:product).permit(:title,:description,:image,:price,:product_description)
  end

  def search
    session[:search_name] ||= params[:search_name]
    session[:filter] = params[:filter]
    params[:filter_option] = nil if params[:filter_option] == ""
    session[:filter_option] = params[:filter_option]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/ecommerces_helper.rb
module EcommercesHelper
end

app/views/auths/index.html.erb
<div class="container bg-white pb-5">
  <div class="row d-flex justify-content-start align-items-center mt-sm-5">
    <div class="col-lg-5 col-10">
      <div id="circle"></div>
      <div class="pb-5"> <img src="https://img.freepik.com/free-vector/authentication-concept-illustration_114360-2168.jpg?size=338&ext=jpg&ga=GA1.2.777073396.1599399655" alt=""> </div>
    </div>
    <div class="col-lg-4 offset-lg-2 col-md-6 offset-md-3">
      <div class="pt-4">
        <h6><span class="fa fa-superpowers text-primary px-md-2"></span>Ecommerce Website</h6>
      </div>
      <div class="mt-3 mt-md-5">
        <h5>Log in to your account</h5>
        <div class="pt-4">
         <%= form_tag(validate_user_path) do %>
            <div class="d-flex flex-column pb-3">
              <label for="email">Email Address</label>
               <%= email_field_tag :email,nil, class: 'border-bottom border-primary' %>
            </div>
            <div class="d-flex flex-column pb-3">
              <label for="password">Password</label>
              <%= password_field_tag :password,nil, class: 'border-bottom border-primary'%>
            </div>
            <div class="d-flex flex-column pb-3">
              <%= submit_tag 'Log In', class: 'btn btn-primary' %>
            </div>
        <%end%>
          <div class="register mt-2">
             <p>Login As <%= link_to "Guest Login", guest_login_path  %></p>
          </div>
          <div class="register mt-2">
            <p>Don't have an account? <%= link_to "Create an account" , new_auth_path%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/auths/new.html.erb
<div class="container bg-white pb-5">
  <div class="row d-flex justify-content-start align-items-center mt-sm-5">
    <div class="col-lg-5 col-10">
      <div id="circle"></div>
      <div class="pb-5">
        <img src="https://img.freepik.com/free-vector/authentication-concept-illustration_114360-2168.jpg?size=338&ext=jpg&ga=GA1.2.777073396.1599399655" alt="">
      </div>
    </div>
    <div class="col-lg-4 offset-lg-2 col-md-6 offset-md-3">
      <div class="pt-4">
        <h6><span class="fa fa-superpowers text-primary px-md-2"></span>Ecommerce Website</h6>
      </div>
      <div class="mt-3 mt-md-5">
        <h5>Sign Up to your Account</h5>
        <% if @user.errors.present? %>
          <ul class="alert alert-danger error_message">
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        <% end %>
        <div class="pt-4">
          <%= form_for(@user, url: auths_path, method: :post) do |f| %>
            <div class="d-flex flex-column pb-3">
              <label for="email">Full Name</label>
              <%= f.text_field :name, class: 'border-bottom border-primary' %>
            </div>
            <div class="d-flex flex-column pb-3">
              <label for="email">Email Address</label>
              <%= f.email_field :email, class: 'border-bottom border-primary' %>
            </div>
            <div class="d-flex flex-column pb-3">
              <label for="password">Password</label>
              <%= f.password_field :password, class: 'border-bottom border-primary' %>
            </div>
            <div class="d-flex flex-column pb-3">
              <label for="password">Confirm Password</label>
              <%= f.password_field :password_confirmation, class: 'border-bottom border-primary' %>
            </div>
            <div class="d-flex flex-column pb-3">
              <%= submit_tag 'Log In', class: 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/index.html.erb
<div class="container-fluid">
  <div class="col-12 col-sm-12">
    <table class="table" style="color: white;">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Price</th>
        <th scope="col">Show</th>
      </tr>
      </thead>
      <tbody>
      <% if @cart.present? %>
      <%counter = 1 %>
        <% @cart.each  do |item| %>
          <tr>
            <th scope="row"><%= counter%></th>
            <td><%= Product.find(item.product_id).title %></td>
            <td><%= Product.find(item.product_id).description %></td>
            <td><%= number_to_currency(Product.find(item.product_id).price) %></td>
            <td><%= link_to "Show", cart_path(id: Product.find(item.product_id).id )  %></td>
          </tr>
      <%counter = counter + 1 %>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/carts/show.html.erb
<section class="banner-bottom py-5">
  <div class="container py-md-5">
    <div class="col-12 col-sm-12">
      <h1> Product Details</h1>
    </div>
    <div class="left-ads-display wthree">
      <div class="row">
        <div class="desc1-left col-md-6">
          <%= image_tag url_for(@product.image) , class:  "img-fluid"%>
        </div>
        <div class="desc1-right col-md-6 pl-lg-3">
          <h3><%= @product.title %></h3>
          <h5>Price: <%= number_to_currency(@product.price) %></h5>
        </div>

      </div>
      <div class="row sub-para-w3pvt my-5">
        <h3 class="shop-sing"><%= @product.title %></h3>
        <p><%= @product.description %>/p>
        <p class="mt-3 italic-blue"><%= @product.product_description %></p>
      </div>
      <h3 class="title-wthree-single my-lg-5 my-4 text-left">Featured Products</h3>
      <div class="row shop-wthree-info text-center">
        <% @products_row.each do |product| %>
          <div class="col-md-3 shop-info-grid text-center mt-4">
            <div class="product-shoe-info shoe">
              <div class="men-thumb-item">
                <%= image_tag url_for(product.image) , class:  "img-fluid"%>
              </div>
              <div class="item-info-product">
                <h4>
                  <a href="single.html"><%= product.title %></a>
                </h4>

                <div class="product_price">
                  <div class="grid-price">
                    <span class="money"><%= number_to_currency(product.price) %></span>
                  </div>
                </div>
                <div class="col-12 col-sm-12">
                  <%= link_to 'Show', ecommerce_path(product.id) , class: 'btn btn-block btn-success' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/ecommerces/index.html.erb
<div class="col-sm-12 col-md-12 col-lg-12 col-12 mb-5">
  <div class="container" style="margin-top: 100px !important;">
    <div class="top-w3pvt d-flex">
      <div id="logo">
        <h1><a href="index.html"><span class="log-w3pvt">E</span>commerce</a>
          <label class="sub-des">Online Store</label></h1>
      </div>
      <% if session[:current_user].nil? || session[:current_user][0]['role'] == "guest" %>
        <div class="forms ml-auto">
          <%= link_to "Sign In", auths_path, class: 'btn' %>
          <%= link_to "Sign Up", new_auth_path,class: "btn" %>
        </div>
      <% else %>
        <% if session[:current_user][0]['role'] == "admin" %>
          <%= link_to 'Add Product', new_ecommerce_path, class: 'btn btn-warning', style: 'color: white;padding-top: 16px;' %>
        <% end %>
        <% if !session[:current_user].nil? %>
          <%= link_to 'Log Out', logout_path, class: 'btn btn-warning', style: 'color:white;padding-top: 16px;' %>
        <% end %>
        <% if !session[:current_user].nil? %>
          <%= link_to 'Cart', carts_path, class: 'btn btn-warning', style: 'color:white;padding-top: 16px;' %>
        <% end %>
      <% end %>
    </div>
    <div class="container-fluid">
      <div class="col-lg-12 col-12">

      </div>
    </div>
    <div class="col-12 col-sm-12">
      <%= form_tag(root_path, method: :get) do %>
        <div class="form-group">
          <%= text_field_tag :search_name, nil, class: 'form-control mr-sm-2', placeholder: 'Search' %>
        </div>
        <div class="form-group" style="margin-top: 10px !important;">
          <%= submit_tag "Search", class: 'btn btn-outline-success my-2 my-sm-0', style: 'width:100%;' %>
        </div>
      <% end %>
    </div>

    <section class="banner-bottom py-5" style="margin-bottom: 100px !important;">
      <div class="container py-5">
        <h3 class="title-wthree mb-lg-5 mb-4 text-center">Shop Now</h3>
        <div class="row shop-wthree-info text-center mb-5">
          <% @products.each do |product| %>
            <div class="col-lg-3 shop-info-grid text-center mt-4">
              <div class="product-shoe-info shoe">
                <div class="men-thumb-item">
                  <%= image_tag url_for(product.image), class: "img-fluid" %>
                </div>
                <div class="item-info-product">
                  <h4>
                    <a href="single.html"><%= product.title %></a>
                  </h4>
                  <div class="product_price">
                    <div class="grid-price">
                      <span class="money"><%= number_to_currency(product.price) %></span>
                    </div>
                  </div>
                  <div class="col-12 col-sm-12">
                    <%= link_to 'Show', ecommerce_path(product.id), class: 'btn btn-block btn-success' %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <nav aria-label="Page navigation example mt-5">
          <ul class="pagination">
            <%= will_paginate @products %>
          </ul>
        </nav>
      </div>
    </section>
  </div>
</div>

app/views/ecommerces/new.html.erb
<div class="container-fluid">
  <div class="col-12 ">
    <h1> Add Product Details</h1>
    <% if @product.errors.present? %>
      <ul class="alert alert-danger error_message">
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for(@product, url: ecommerces_path, class: 'mt-5 mb-5') do |f| %>
      <div class="form-group" >
        <label style="color:white; margin-top: 20px !important;" >Title</label>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter the title', style: "margin-top: 10px;!important;" %>
      </div>
      <div class="form-group">
        <label style="color:white;">Product Description</label>
        <%= f.text_area :product_description, class: 'form-control', placeholder: 'Enter the Description' , style: "margin-top: 10px;!important;"%>
      </div>
      <div class="form-group">
        <label style="color:white;">Description</label>
        <%= f.text_area :description, class: 'form-control', placeholder: 'Enter the Description', style: "margin-top: 10px;!important;" %>
      </div>
      <div class="form-group">
        <label style="color:white;">Price</label>
        <%= f.number_field :price, class: 'form-control', placeholder: 'Enter the Price', style: "margin-top: 10px;!important;" %>
      </div>
      <div class="form-group">
        <label style="color:white;">Image</label>
        <%= f.file_field :image, class: 'form-control', placeholder: 'Upload Image', style: "margin-top: 10px;!important;" %>
      </div>
      <div class="offset-4 col-4 " style="margin-top: 10px;!important; margin-bottom: 40px;!important;">
         <%= f.submit "Add Product", class: 'btn btn-success', style: 'width:100% !important' %>
      </div>
    <% end %>
  </div>
</div>

app/views/ecommerces/show.html.erb
<section class="banner-bottom py-5">
  <div class="container py-md-5">
    <div class="col-12 col-sm-12">
      <h1> Product Details</h1>
    </div>
    <div class="left-ads-display wthree">
      <div class="row">
        <div class="desc1-left col-md-6">
          <%= image_tag url_for(@product.image) , class:  "img-fluid"%>
        </div>
        <div class="desc1-right col-md-6 pl-lg-3">
          <h3><%= @product.title %></h3>
          <h5>Price: <%= number_to_currency(@product.price) %></h5>
          <div class="available mt-3">
            <form action="#" method="post" class="w3pvt-newsletter subscribe-sec">
               <%= link_to 'Add TO CART', "#", class: 'btn btn-block btn-primary' %>
            </form>
            <% if session[:current_user].count < 0 %>
                 <span><%= link_to 'Login To Buy the Product ', auths_path %></span>
              <%end%>
          </div>
        </div>

      </div>
      <div class="row sub-para-w3pvt my-5">
        <h3 class="shop-sing"><%= @product.title %></h3>
        <p><%= @product.description %>/p>
        <p class="mt-3 italic-blue"><%= @product.product_description %></p>
      </div>
      <h3 class="title-wthree-single my-lg-5 my-4 text-left">Featured Products</h3>
      <div class="row shop-wthree-info text-center">
        <% @products_row.each do |product| %>
          <div class="col-md-3 shop-info-grid text-center mt-4">
            <div class="product-shoe-info shoe">
              <div class="men-thumb-item">
                <%= image_tag url_for(product.image) , class:  "img-fluid"%>
              </div>
              <div class="item-info-product">
                <h4>
                  <a href="single.html"><%= product.title %></a>
                </h4>

                <div class="product_price">
                  <div class="grid-price">
                    <span class="money"><%= number_to_currency(product.price) %></span>
                  </div>
                </div>
                <div class="col-12 col-sm-12">
                  <%= link_to 'Show', ecommerce_path(product.id) , class: 'btn btn-block btn-success' %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecommerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid" style="background-color: #6610f2;">
    <%= yield %>
  </body>
</html>